version: '2'
services:
  db:
    image: mysql:5.7.22
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/volumes:/var/lib/mysql
    extends:
      file: ./docker/mysql/password.yml
      service: password
  server:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - '80:80'
  web:
    build:
      context: .
      dockerfile: ./docker/rails/Dockerfile
    command: bundle exec unicorn -p 3000 -c config/unicorn.rb
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    extends:
      file: ./docker/mysql/password.yml
      service: password
    links:
      - db